// Generated by CoffeeScript 1.6.3
var initEnvironment, initialize, populateUserData, pupOnline;

pupOnline = function() {
  return API.sendChat("Bot Online!");
};

populateUserData = function() {
  var u, users, _i, _len;
  users = API.getUsers();
  for (_i = 0, _len = users.length; _i < _len; _i++) {
    u = users[_i];
    data.users[u.id] = new User(u);
    data.voteLog[u.id] = {};
  }
};

initEnvironment = function() {
  document.getElementById("button-vote-positive").click();
  return document.getElementById("button-sound").click();
};

initialize = function() {
  pupOnline();
  populateUserData();
  initEnvironment();
  initHooks();
  data.startup();
  data.newSong();
  return data.startAfkInterval();
};
