// Generated by CoffeeScript 1.6.3
var dieCommand, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

dieCommand = (function(_super) {
  __extends(dieCommand, _super);

  function dieCommand() {
    _ref = dieCommand.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  dieCommand.prototype.init = function() {
    this.command = '!die';
    this.parseType = 'exact';
    return this.rankPrivelege = 'host';
  };

  dieCommand.prototype.functionality = function() {
    API.sendChat('Unhooking Events...');
    undoHooks();
    API.sendChat('Deleting bot data...');
    data.implode();
    return API.sendChat('Consider me dead');
  };

  return dieCommand;

})(Command);
