// Generated by CoffeeScript 1.6.3
var unhookCommand, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

unhookCommand = (function(_super) {
  __extends(unhookCommand, _super);

  function unhookCommand() {
    _ref = unhookCommand.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  unhookCommand.prototype.init = function() {
    this.command = '!unhook events all';
    this.parseType = 'exact';
    return this.rankPrivelege = 'host';
  };

  unhookCommand.prototype.functionality = function() {
    API.sendChat('Unhooking all events...');
    return undoHooks();
  };

  return unhookCommand;

})(Command);
