// Generated by CoffeeScript 1.6.3
var unlockCommand, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

unlockCommand = (function(_super) {
  __extends(unlockCommand, _super);

  function unlockCommand() {
    _ref = unlockCommand.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  unlockCommand.prototype.init = function() {
    this.command = '!unlock';
    this.parseType = 'exact';
    return this.rankPrivelege = 'mod';
  };

  unlockCommand.prototype.functionality = function() {
    return data.unlockBooth();
  };

  return unlockCommand;

})(Command);
